table trail_system
	lineageTag: 3633c61a-d4fc-44a0-90a7-c57a48520bda

	column trail_system_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f113a4de-d008-4281-9186-7bf0c5a25612
		summarizeBy: none
		sourceColumn: trail_system_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column trail_system_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 89829f7c-5760-4960-93b4-ae32cb2a0453
		summarizeBy: none
		sourceColumn: trail_system_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column trail_system_name
		dataType: string
		lineageTag: 22194338-6f29-4966-9037-5ef020efd573
		summarizeBy: none
		sourceColumn: trail_system_name

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: b7c73d0c-8ec8-499e-8d94-84e8d200e390
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 81bfbe8f-73c5-46a2-90fc-34a4173ccdbc
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 85468c94-e4b6-44ed-b9cc-46e4961f6502
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: string
		lineageTag: 6c438ba7-d6dc-4af1-966f-f160c7cb7143
		summarizeBy: none
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: string
		lineageTag: 9ae9b8c2-bade-4754-ace8-91cb9661c31f
		summarizeBy: none
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 787c542b-f023-4456-8d14-bd1f1bb744c9
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column osm_element_type
		dataType: string
		lineageTag: bf764639-50a3-4a69-8e0f-96eca5fc0f21
		summarizeBy: none
		sourceColumn: osm_element_type

		annotation SummarizationSetBy = Automatic

	column osm_element_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 6c9aa4c5-26e3-416e-873c-ef31556487e6
		summarizeBy: none
		sourceColumn: osm_element_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column osm_display_name
		dataType: string
		lineageTag: 37606136-c73f-412f-8693-dcb4e064b098
		summarizeBy: none
		sourceColumn: osm_display_name

		annotation SummarizationSetBy = Automatic

	column boundary_source
		dataType: string
		lineageTag: 6f3b6ac4-9fab-44bb-a784-4726682988fe
		summarizeBy: none
		sourceColumn: boundary_source

		annotation SummarizationSetBy = Automatic

	column boundary_confirmed
		dataType: int64
		formatString: 0
		lineageTag: 0e4450f1-78b7-456b-8ab7-e7f5c9116067
		summarizeBy: none
		sourceColumn: boundary_confirmed

		annotation SummarizationSetBy = Automatic

	column boundary_updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: d6766115-1afd-4364-adab-a410398c7c65
		summarizeBy: none
		sourceColumn: boundary_updated_at

		annotation SummarizationSetBy = Automatic

	column official_trail_count
		dataType: int64
		formatString: 0
		lineageTag: 3770bc35-c44c-470a-ad6b-0435a326dffb
		summarizeBy: none
		sourceColumn: official_trail_count

		annotation SummarizationSetBy = Automatic

	column assigned_osm_section_count
		dataType: int64
		formatString: 0
		lineageTag: c56fa4dd-2b79-4427-a8b2-db9b8111885e
		summarizeBy: none
		sourceColumn: assigned_osm_section_count

		annotation SummarizationSetBy = Automatic

	column official_trail_length_miles
		dataType: double
		lineageTag: f6a0315d-40b0-43d2-adc9-8936bc78535f
		summarizeBy: none
		sourceColumn: official_trail_length_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column completed_trail_count
		dataType: int64
		formatString: 0
		lineageTag: 14981c00-31c8-4c63-9fc6-b44b427b0afc
		summarizeBy: none
		sourceColumn: completed_trail_count

		annotation SummarizationSetBy = Automatic

	column nearly_complete_trail_count
		dataType: int64
		formatString: 0
		lineageTag: ed0de6ec-0cdd-48b5-b45d-87b6dc9f9d87
		summarizeBy: none
		sourceColumn: nearly_complete_trail_count

		annotation SummarizationSetBy = Automatic

	column partial_trail_count
		dataType: int64
		formatString: 0
		lineageTag: acf9fdf7-d83e-4beb-b76b-ac6f64e5d3f3
		summarizeBy: none
		sourceColumn: partial_trail_count

		annotation SummarizationSetBy = Automatic

	column started_trail_count
		dataType: int64
		formatString: 0
		lineageTag: 64600977-dcc1-4ae0-ac19-124204b6d74c
		summarizeBy: none
		sourceColumn: started_trail_count

		annotation SummarizationSetBy = Automatic

	column unridden_trail_count
		dataType: int64
		formatString: 0
		lineageTag: 40ccc764-42e6-4caf-9398-f44a9156d6cf
		summarizeBy: none
		sourceColumn: unridden_trail_count

		annotation SummarizationSetBy = Automatic

	column unique_covered_distance_miles
		dataType: double
		lineageTag: ebac1f6a-19c1-4465-a13d-f24005494f8f
		summarizeBy: none
		sourceColumn: unique_covered_distance_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column remaining_distance_miles
		dataType: double
		lineageTag: bd6d91da-5448-41ea-a190-af4a6b59c75e
		summarizeBy: none
		sourceColumn: remaining_distance_miles

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighted_completion_percent
		dataType: double
		lineageTag: d1ae2ab2-3b11-41d6-85fd-2b6c6b7599dc
		summarizeBy: none
		sourceColumn: weighted_completion_percent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column created_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 57097039-d8c2-4dba-a9ef-7a6983b5c4b2
		summarizeBy: none
		sourceColumn: created_at

		annotation SummarizationSetBy = Automatic

	column updated_at
		dataType: dateTime
		formatString: General Date
		lineageTag: 653deea3-3b61-49fb-aef2-a322dfdf6f54
		summarizeBy: none
		sourceColumn: updated_at

		annotation SummarizationSetBy = Automatic

	partition trail_system = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\AustinEngstrom\Documents\GitHub\activity_tracking\exports\power_bi\view_trail_system.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"trail_system_key", Int64.Type}, {"trail_system_id", Int64.Type}, {"trail_system_name", type text}, {"city", type text}, {"state", type text}, {"country", type text}, {"latitude", type any}, {"longitude", type any}, {"description", type any}, {"osm_element_type", type text}, {"osm_element_id", Int64.Type}, {"osm_display_name", type text}, {"boundary_source", type text}, {"boundary_confirmed", Int64.Type}, {"boundary_updated_at", type datetimezone}, {"official_trail_count", Int64.Type}, {"assigned_osm_section_count", Int64.Type}, {"official_trail_length_miles", type number}, {"completed_trail_count", Int64.Type}, {"nearly_complete_trail_count", Int64.Type}, {"partial_trail_count", Int64.Type}, {"started_trail_count", Int64.Type}, {"unridden_trail_count", Int64.Type}, {"unique_covered_distance_miles", type number}, {"remaining_distance_miles", type number}, {"weighted_completion_percent", type number}, {"created_at", type datetimezone}, {"updated_at", type datetimezone}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

