"""add activity streams table

Revision ID: 2fd859810c1c
Revises: acbe2eb473e1
Create Date: 2026-08-02 21:39:26.425312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd859810c1c'
down_revision: Union[str, Sequence[str], None] = 'acbe2eb473e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_streams',
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('point_index', sa.Integer(), nullable=False),
    sa.Column('time_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude_meters', sa.Float(), nullable=True),
    sa.Column('velocity_mps', sa.Float(), nullable=True),
    sa.Column('heartrate', sa.Integer(), nullable=True),
    sa.Column('cadence', sa.Float(), nullable=True),
    sa.Column('watts', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('is_moving', sa.Boolean(), nullable=True),
    sa.Column('grade_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'point_index', name='pk_activity_streams')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_streams')
    # ### end Alembic commands ###
