"""add trail systems

Revision ID: 40e3a1fd57a5
Revises: aa562dcefa4e
Create Date: 2026-08-04 14:03:58.130519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e3a1fd57a5'
down_revision: Union[str, Sequence[str], None] = 'aa562dcefa4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trail_systems',
    sa.Column('trail_system_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('trail_system_id')
    )
    with op.batch_alter_table('trail_systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trail_systems_name'), ['name'], unique=True)

    op.create_table('segment_trail_systems',
    sa.Column('segment_trail_system_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('segment_id', sa.BigInteger(), nullable=False),
    sa.Column('trail_system_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mapping_source', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 and confidence <= 1.0', name='ck_segment_trail_system_confidence'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.segment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trail_system_id'], ['trail_systems.trail_system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('segment_trail_system_id'),
    sa.UniqueConstraint('segment_id', 'trail_system_id', name='uq_segment_trail_system')
    )
    with op.batch_alter_table('segment_trail_systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segment_trail_systems_segment_id'), ['segment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_segment_trail_systems_trail_system_id'), ['trail_system_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment_trail_systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segment_trail_systems_trail_system_id'))
        batch_op.drop_index(batch_op.f('ix_segment_trail_systems_segment_id'))

    op.drop_table('segment_trail_systems')
    with op.batch_alter_table('trail_systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trail_systems_name'))

    op.drop_table('trail_systems')
    # ### end Alembic commands ###
