"""add osm trail boundaries


Revision ID: 6d57cb1dffd3
Revises: 80eaf2e859bc
Create Date: 2026-08-05 08:02:17.086723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d57cb1dffd3'
down_revision: Union[str, Sequence[str], None] = '80eaf2e859bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    with op.batch_alter_table(
        "trail_systems",
        schema=None,
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "boundary_confirmed",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

        batch_op.add_column(
            sa.Column(
                "boundary_updated_at",
                sa.DateTime(),
                nullable=True,
            )
        )
        
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail_systems', schema=None) as batch_op:
        batch_op.drop_column('boundary_updated_at')
        batch_op.drop_column('boundary_confirmed')
        batch_op.drop_column('boundary_source')
        batch_op.drop_column('boundary_geojson')
        batch_op.drop_column('osm_display_name')
        batch_op.drop_column('osm_element_id')
        batch_op.drop_column('osm_element_type')

    # ### end Alembic commands ###
