"""add trail segment mappings

Revision ID: 6f09ffa30760
Revises: 784c53542fb9
Create Date: 2026-08-05 10:28:07.663208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f09ffa30760'
down_revision: Union[str, Sequence[str], None] = '784c53542fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trail_segment_mappings',
    sa.Column('trail_segment_mapping_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('osm_trail_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.BigInteger(), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('overlap_percent', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mapping_source', sa.String(length=50), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['osm_trail_id'], ['osm_trails.osm_trail_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.segment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trail_segment_mapping_id'),
    sa.UniqueConstraint('osm_trail_id', 'segment_id', name='uq_osm_trail_segment')
    )
    with op.batch_alter_table('trail_segment_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trail_segment_mappings_osm_trail_id'), ['osm_trail_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trail_segment_mappings_segment_id'), ['segment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail_segment_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trail_segment_mappings_segment_id'))
        batch_op.drop_index(batch_op.f('ix_trail_segment_mappings_osm_trail_id'))

    op.drop_table('trail_segment_mappings')
    # ### end Alembic commands ###
