"""add osm trails

Revision ID: 784c53542fb9
Revises: 6d57cb1dffd3
Create Date: 2026-08-05 10:15:23.747737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784c53542fb9'
down_revision: Union[str, Sequence[str], None] = '6d57cb1dffd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('osm_trails',
    sa.Column('osm_trail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trail_system_id', sa.Integer(), nullable=False),
    sa.Column('osm_element_type', sa.String(length=20), nullable=False),
    sa.Column('osm_element_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('highway_type', sa.String(length=50), nullable=True),
    sa.Column('surface', sa.String(length=100), nullable=True),
    sa.Column('bicycle_access', sa.String(length=50), nullable=True),
    sa.Column('access', sa.String(length=50), nullable=True),
    sa.Column('mtb_scale', sa.String(length=50), nullable=True),
    sa.Column('mtb_scale_uphill', sa.String(length=50), nullable=True),
    sa.Column('mtb_type', sa.String(length=50), nullable=True),
    sa.Column('oneway', sa.String(length=20), nullable=True),
    sa.Column('length_meters', sa.Float(), nullable=True),
    sa.Column('vertex_count', sa.Integer(), nullable=True),
    sa.Column('is_loop', sa.Boolean(), nullable=True),
    sa.Column('geometry_geojson', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trail_system_id'], ['trail_systems.trail_system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('osm_trail_id'),
    sa.UniqueConstraint('trail_system_id', 'osm_element_type', 'osm_element_id', name='uq_osm_trail_system_element')
    )
    with op.batch_alter_table('osm_trails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_osm_trails_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_osm_trails_osm_element_id'), ['osm_element_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_osm_trails_trail_system_id'), ['trail_system_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('osm_trails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_osm_trails_trail_system_id'))
        batch_op.drop_index(batch_op.f('ix_osm_trails_osm_element_id'))
        batch_op.drop_index(batch_op.f('ix_osm_trails_name'))

    op.drop_table('osm_trails')
    # ### end Alembic commands ###
