"""add trail mapping rules

Revision ID: 80eaf2e859bc
Revises: 40e3a1fd57a5
Create Date: 2026-08-05 07:24:49.471396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80eaf2e859bc'
down_revision: Union[str, Sequence[str], None] = '40e3a1fd57a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trail_mapping_rules',
    sa.Column('rule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trail_system_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('match_value', sa.String(length=255), nullable=True),
    sa.Column('min_latitude', sa.Float(), nullable=True),
    sa.Column('max_latitude', sa.Float(), nullable=True),
    sa.Column('min_longitude', sa.Float(), nullable=True),
    sa.Column('max_longitude', sa.Float(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 and confidence <= 1.0', name='ck_trail_mapping_rule_confidence'),
    sa.CheckConstraint('priority >= 0', name='ck_trail_mapping_rule_priority'),
    sa.ForeignKeyConstraint(['trail_system_id'], ['trail_systems.trail_system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id')
    )
    with op.batch_alter_table('trail_mapping_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trail_mapping_rules_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_trail_mapping_rules_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_trail_mapping_rules_rule_type'), ['rule_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_trail_mapping_rules_trail_system_id'), ['trail_system_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trail_mapping_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trail_mapping_rules_trail_system_id'))
        batch_op.drop_index(batch_op.f('ix_trail_mapping_rules_rule_type'))
        batch_op.drop_index(batch_op.f('ix_trail_mapping_rules_priority'))
        batch_op.drop_index(batch_op.f('ix_trail_mapping_rules_active'))

    op.drop_table('trail_mapping_rules')
    # ### end Alembic commands ###
