"""add official trail gps progress

Revision ID: 8cce63d090ff
Revises: b49e16fc6247
Create Date: 2026-08-05 12:55:54.436614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cce63d090ff'
down_revision: Union[str, Sequence[str], None] = 'b49e16fc6247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('official_trail_activity_matches',
    sa.Column('official_trail_activity_match_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('official_trail_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('matched_trail_length_meters', sa.Float(), nullable=False),
    sa.Column('ridden_distance_meters', sa.Float(), nullable=False),
    sa.Column('trail_coverage_percent', sa.Float(), nullable=False),
    sa.Column('matched_point_count', sa.Integer(), nullable=False),
    sa.Column('tolerance_meters', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['official_trail_id'], ['official_trails.official_trail_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('official_trail_activity_match_id'),
    sa.UniqueConstraint('official_trail_id', 'activity_id', name='uq_official_trail_activity')
    )
    with op.batch_alter_table('official_trail_activity_matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_official_trail_activity_matches_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_official_trail_activity_matches_official_trail_id'), ['official_trail_id'], unique=False)

    op.create_table('official_trail_progress',
    sa.Column('official_trail_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('activity_count', sa.Integer(), nullable=False),
    sa.Column('first_ridden_at', sa.DateTime(), nullable=True),
    sa.Column('last_ridden_at', sa.DateTime(), nullable=True),
    sa.Column('total_ridden_distance_meters', sa.Float(), nullable=False),
    sa.Column('estimated_coverage_percent', sa.Float(), nullable=False),
    sa.Column('progress_status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['official_trail_id'], ['official_trails.official_trail_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('official_trail_id')
    )
    with op.batch_alter_table('official_trail_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_official_trail_progress_progress_status'), ['progress_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('official_trail_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_official_trail_progress_progress_status'))

    op.drop_table('official_trail_progress')
    with op.batch_alter_table('official_trail_activity_matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_official_trail_activity_matches_official_trail_id'))
        batch_op.drop_index(batch_op.f('ix_official_trail_activity_matches_activity_id'))

    op.drop_table('official_trail_activity_matches')
    # ### end Alembic commands ###
