"""add gear table

Revision ID: a774e82031aa
Revises: f8e8d123179a
Create Date: 2026-08-02 20:22:25.212736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a774e82031aa'
down_revision: Union[str, Sequence[str], None] = 'f8e8d123179a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gear',
    sa.Column('gear_id', sa.String(length=50), nullable=False),
    sa.Column('athlete_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('is_retired', sa.Boolean(), nullable=True),
    sa.Column('detail_loaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('gear_id')
    )
    with op.batch_alter_table('gear', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gear_athlete_id'), ['athlete_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gear_athlete_id'))

    op.drop_table('gear')
    # ### end Alembic commands ###
