"""add activity enrichment tracking

Revision ID: aa562dcefa4e
Revises: cc0fd8b4480b
Create Date: 2026-08-03 09:10:54.066545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa562dcefa4e'
down_revision: Union[str, Sequence[str], None] = 'cc0fd8b4480b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segments_loaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('laps_loaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('splits_loaded_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_activities_detail_loaded_at'), ['detail_loaded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_laps_loaded_at'), ['laps_loaded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_segments_loaded_at'), ['segments_loaded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_splits_loaded_at'), ['splits_loaded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_splits_loaded_at'))
        batch_op.drop_index(batch_op.f('ix_activities_segments_loaded_at'))
        batch_op.drop_index(batch_op.f('ix_activities_laps_loaded_at'))
        batch_op.drop_index(batch_op.f('ix_activities_detail_loaded_at'))
        batch_op.drop_column('splits_loaded_at')
        batch_op.drop_column('laps_loaded_at')
        batch_op.drop_column('segments_loaded_at')

    # ### end Alembic commands ###
