"""add frame type to gear

Revision ID: acbe2eb473e1
Revises: a774e82031aa
Create Date: 2026-08-02 21:10:35.337473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbe2eb473e1'
down_revision: Union[str, Sequence[str], None] = 'a774e82031aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frame_type', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gear', schema=None) as batch_op:
        batch_op.drop_column('frame_type')

    # ### end Alembic commands ###
