"""add official trails

Revision ID: b49e16fc6247
Revises: 6f09ffa30760
Create Date: 2026-08-05 10:53:35.493352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49e16fc6247'
down_revision: Union[str, Sequence[str], None] = '6f09ffa30760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('official_trails',
    sa.Column('official_trail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trail_system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('total_length_meters', sa.Float(), nullable=False),
    sa.Column('section_count', sa.Integer(), nullable=False),
    sa.Column('primary_surface', sa.String(length=100), nullable=True),
    sa.Column('bicycle_access', sa.String(length=50), nullable=True),
    sa.Column('mtb_scale', sa.String(length=50), nullable=True),
    sa.Column('mtb_type', sa.String(length=50), nullable=True),
    sa.Column('combined_geometry_geojson', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trail_system_id'], ['trail_systems.trail_system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('official_trail_id'),
    sa.UniqueConstraint('trail_system_id', 'normalized_name', name='uq_official_trail_system_name')
    )
    with op.batch_alter_table('official_trails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_official_trails_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_official_trails_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_official_trails_trail_system_id'), ['trail_system_id'], unique=False)

    with op.batch_alter_table('osm_trails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('official_trail_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_osm_trails_official_trail_id'), ['official_trail_id'], unique=False)
        batch_op.create_foreign_key(None, 'official_trails', ['official_trail_id'], ['official_trail_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('osm_trails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_osm_trails_official_trail_id'))
        batch_op.drop_column('official_trail_id')

    with op.batch_alter_table('official_trails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_official_trails_trail_system_id'))
        batch_op.drop_index(batch_op.f('ix_official_trails_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_official_trails_name'))

    op.drop_table('official_trails')
    # ### end Alembic commands ###
