"""add segments and segment efforts

Revision ID: cc0fd8b4480b
Revises: 2fd859810c1c
Create Date: 2026-08-03 08:39:07.764940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0fd8b4480b'
down_revision: Union[str, Sequence[str], None] = '2fd859810c1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segments',
    sa.Column('segment_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('average_grade', sa.Float(), nullable=True),
    sa.Column('maximum_grade', sa.Float(), nullable=True),
    sa.Column('elevation_high_meters', sa.Float(), nullable=True),
    sa.Column('elevation_low_meters', sa.Float(), nullable=True),
    sa.Column('start_latitude', sa.Float(), nullable=True),
    sa.Column('start_longitude', sa.Float(), nullable=True),
    sa.Column('end_latitude', sa.Float(), nullable=True),
    sa.Column('end_longitude', sa.Float(), nullable=True),
    sa.Column('climb_category', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('hazardous', sa.Boolean(), nullable=True),
    sa.Column('starred', sa.Boolean(), nullable=True),
    sa.Column('effort_count', sa.Integer(), nullable=True),
    sa.Column('athlete_count', sa.Integer(), nullable=True),
    sa.Column('star_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('segment_id')
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segments_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_segments_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_segments_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_segments_state'), ['state'], unique=False)

    op.create_table('segment_efforts',
    sa.Column('segment_effort_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('segment_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('elapsed_time_seconds', sa.Integer(), nullable=False),
    sa.Column('moving_time_seconds', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('start_date_local', sa.DateTime(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('start_index', sa.Integer(), nullable=True),
    sa.Column('end_index', sa.Integer(), nullable=True),
    sa.Column('average_cadence', sa.Float(), nullable=True),
    sa.Column('average_watts', sa.Float(), nullable=True),
    sa.Column('device_watts', sa.Boolean(), nullable=True),
    sa.Column('average_heartrate', sa.Float(), nullable=True),
    sa.Column('max_heartrate', sa.Float(), nullable=True),
    sa.Column('kom_rank', sa.Integer(), nullable=True),
    sa.Column('pr_rank', sa.Integer(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.activity_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.segment_id'], ),
    sa.PrimaryKeyConstraint('segment_effort_id')
    )
    with op.batch_alter_table('segment_efforts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_segment_efforts_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_segment_efforts_segment_id'), ['segment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_segment_efforts_start_date'), ['start_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment_efforts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segment_efforts_start_date'))
        batch_op.drop_index(batch_op.f('ix_segment_efforts_segment_id'))
        batch_op.drop_index(batch_op.f('ix_segment_efforts_activity_id'))

    op.drop_table('segment_efforts')
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_segments_state'))
        batch_op.drop_index(batch_op.f('ix_segments_name'))
        batch_op.drop_index(batch_op.f('ix_segments_city'))
        batch_op.drop_index(batch_op.f('ix_segments_activity_type'))

    op.drop_table('segments')
    # ### end Alembic commands ###
