"""add detailed activity fields

Revision ID: f8e8d123179a
Revises: ce7d921c8d9a
Create Date: 2026-07-30 20:03:32.569998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e8d123179a'
down_revision: Union[str, Sequence[str], None] = 'ce7d921c8d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('calories', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('device_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('workout_type', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('suffer_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('average_cadence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_heartrate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('has_heartrate', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('detail_loaded_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('detail_loaded_at')
        batch_op.drop_column('has_heartrate')
        batch_op.drop_column('max_heartrate')
        batch_op.drop_column('average_cadence')
        batch_op.drop_column('suffer_score')
        batch_op.drop_column('workout_type')
        batch_op.drop_column('device_name')
        batch_op.drop_column('calories')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
